In [209]:
import numpy as np

In [283]:
# ALL ZEROS
# np.zeros((2, 3, 3, 2))

# new = np.arange(1,31)
# new = np.reshape(5, 6)
# print(new)

# a = new.reshape((5, 6))
# print(a)




[1, 4]


In [ ]:
# a1 = np.array([[1,2,3,4,5],
#              [6,7,8,9,10]])


# a2 = np.array([[11,12,13,14,15],
#              [16,17,18,19,20]])

# a = np.concatenate((a1, a2), axis=1)

# print(a)



# print(a.reshape((2, 2, 5)))
# print(a.reshape((2, 5, 2)))
# print(a.reshape((5, 2, 2)))

# a = a.reshape(5, 4)
# a.resize(2,10)
# print(a)

# print(a.flatten())
# print(a.ravel())

# var1 = a.flatten()

#TRANSPOSING
# print(a.T)
# print(a.swapaxes(0, 1))

# a = np.array([[1,2,3,4,5],
#              [6,7,8,9,10],
#              [11,12,13,14,15],
#              [16,17,18,19,20]])

# a = np.concatenate((a1, a2), axis=1)

# print(np.split(a,2, axis=0))
# print(a.min())
# print(a.max())
# print(a.mean())
# print(a.std())
# print(a.sum())
# print(np.median(a))

# RANDOM ARRAYS
# numbers = np.random.randint(90, 100, size=(2,3,4))
# print(numbers)

# numbers = np.random.normal(loc=170, scale=15, size=(5, 10))
# print(numbers)

# numbers = np.random.choice([10,20,30,40,50], size=(5, 10))
# print(numbers)

# a = np.array([[40, 50, 50, 30, 10, 10, 50, 10],
#               [40, 50, 50, 30, 10, 10, 50, 10],
#              [40, 50, 50, 30, 10, 10, 50, 10],
#              [40, 50, 50, 30, 10, 10, 50, 10],
#              [40, 50, 50, 30, 10, 10, 50, 10]])

# a = a.reshape(4, 10)

# print(a)

# np.save("myarray.npy", a)

# a = np.load("myarray.npy")
# print(a)

# np.savetxt("myarray.csv", a, delimiter=" ,")


# a = np.loadtxt("myarray.csv", delimiter=",")
               
# print(a)









In [197]:
#stop value np.arange(stop)
np.arange(8)
my_array = np.arange(8)
my_array = np.arange(1,8)
my_array = np.arange(-1, 9.25, 0.5)

print(my_array)
print(type(my_array))

[-1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5
  6.   6.5  7.   7.5  8.   8.5  9. ]
<class 'numpy.ndarray'>


In [180]:
#array from list(FOR MEMORY EFFICIENCY)
#A BOOLEAN TAKES LESSER SPACE THAN STRINGS. A BOOLEAN is either true or false.
#BOOLEAN....Either TRUE or FALSE
#A STRING--either of 26 lowercase char,or 26 uppercase char,either of 10 digits
#either of 10+ punctuation symbols. Over 70 options
from_list = np.array([1,2,3],dtype=np.int8)
print(type(from_list[0]))




<class 'numpy.int8'>


In [38]:
#ROWS AND COLMUNS DATA(TWO DIMENSIONAL ARRAY)
from_list = np.array([[1,2,3],[4,5,6]],dtype=np.int8)
#print(from_list)
array_2d = np.array((np.arange(0,8,2), np.arange(1,8,2)))
array_2d = array_2d.reshape((2, 2, 2)) 
print(array_2d)
#print("1D shape:", my_array.shape)
print("2D shape:", array_2d.shape)
# print(array_2d)


[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
2D shape: (2, 2, 2)


In [70]:
#NUMPY HAS 3 DIFF FUNCT TO CREATE EMPTY ARRAYS
#FIRST IS np.zero
empty_array = np.zeros((2,2))
#print(empty_array)

#SECOND IS 
empty_array = np.ones((2,2))

#print(empty_array)


#THIRD IS np.empty
#EMPTY RETURNS RANDOMS VALUES
empty_array = np.empty((2, 2, 2))
#print(empty_array)

#ANOTHER TYPE OF ARRAY IS NP.EYE\
#THIS CAN ALSO BE MANIPULATED AND CHANGE OF VALUES
eye_array = np.eye(3)
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
eye_array[eye_array < 2] = 9
eye_array[1:] = 3
eye_array[1:, :2] = 4
#print(eye_array, "\n")
sorted_array = np.sort(eye_array, axis=0, kind="heapsort")
#also there is "mergesort"
#print(sorted_array)
#THERE ARE 2 DIFF METHODS TO MAKE COPIES OF ARRAYS
#1.VIEW 2. COPY
my_view = sorted_array.view()
my_copy = sorted_array.copy()

my_copy[:] = 4
my_view = my_view.reshape((3,3,1))
print(my_view, "\n")
print(sorted_array)

#KEYNOTE
#the view modify the value and the original array.
#the copy made changes but the original array stands
#even if we change the view it doesn'tm affect the original array unless we cvhange the value








[[[2.]
  [4.]
  [2.]]

 [[4.]
  [4.]
  [3.]]

 [[4.]
  [9.]
  [3.]]] 

[[2. 4. 2.]
 [4. 4. 3.]
 [4. 9. 3.]]


In [118]:
# a_mul = np.array([[1,2,3,1],
#                  [4,5,6,1],
#                  [7,8,9,1]])

# print(a_mul.shape)
# print(a_mul.ndim)
# print(a_mul.size)
# print(a_mul.dtype)

# d = {'1': 'A'}

# a = np.array([[1,2,3],
#              [4, d, 6],
#              [7,8,9]], dtype="<U2")

# print(a.dtype)
# print(type(a[1][0]))

# a = np.full((2,3,4), 9)
# print(a)


# a = np.zeros((10, 5, 2))
# print(a)

# a = np.empty((2,3,3))
# print(a)

# x_values = np.arange(0,1000,5)
# print(x_values)

# x_values = np.linspace(2,100,4)
# print(x_values)

# print(np.nan)
# print(np.inf)

# print(np.sqrt(-1))
# print(np.array([10]) / 0)
#CALCULATIONS USING NUMPY ARRAYS

# l1 = [1,2,3,4,5]

# l2 = [6,7,8,9,0]

# a1 = np.array(l1)
# a2 = np.array(l2)

# # print(l1 * 5)
# # print(a1 + 5)
# print( a1 + a2)

# a1 = np.array([1,2,3])
# a2 = np.array([[1],
#               [2]])
# print(a1 + a2)

a = np.array([[123,],
            [4,5,6]])

print(np.)

[[2 3 4]
 [3 4 5]]
