In [22]:
import numpy as np

In [23]:
mmm = np.array([1,2,3,'6',False, 3.5], dtype='int32')
mmm

array([1, 2, 3, 6, 0, 3])

In [3]:
# create array of string setting dtype to string
o =np.array(['name', 'location','address', 'phone', 8.9], dtype='<U')
o

array(['name', 'location', 'address', 'phone', '8.9'], dtype='<U8')

In [21]:

a = np.arange(100).reshape(10, 10)
a


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [14]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.zeros((10,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
np.ones((12,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [30]:
np.full((7,9), 8)

array([[8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [32]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [40]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [47]:
np.linspace(3, 50, 120)

array([ 3.        ,  3.39495798,  3.78991597,  4.18487395,  4.57983193,
        4.97478992,  5.3697479 ,  5.76470588,  6.15966387,  6.55462185,
        6.94957983,  7.34453782,  7.7394958 ,  8.13445378,  8.52941176,
        8.92436975,  9.31932773,  9.71428571, 10.1092437 , 10.50420168,
       10.89915966, 11.29411765, 11.68907563, 12.08403361, 12.4789916 ,
       12.87394958, 13.26890756, 13.66386555, 14.05882353, 14.45378151,
       14.8487395 , 15.24369748, 15.63865546, 16.03361345, 16.42857143,
       16.82352941, 17.21848739, 17.61344538, 18.00840336, 18.40336134,
       18.79831933, 19.19327731, 19.58823529, 19.98319328, 20.37815126,
       20.77310924, 21.16806723, 21.56302521, 21.95798319, 22.35294118,
       22.74789916, 23.14285714, 23.53781513, 23.93277311, 24.32773109,
       24.72268908, 25.11764706, 25.51260504, 25.90756303, 26.30252101,
       26.69747899, 27.09243697, 27.48739496, 27.88235294, 28.27731092,
       28.67226891, 29.06722689, 29.46218487, 29.85714286, 30.25

In [49]:
np.random.random((4,4))

array([[0.48604839, 0.95442163, 0.42922261, 0.02878383],
       [0.85390395, 0.73966801, 0.974429  , 0.09697683],
       [0.01675226, 0.98040249, 0.97059889, 0.22793841],
       [0.49845955, 0.99385683, 0.13609053, 0.75162204]])

In [56]:

np.random.normal(2,3,(2,3))

array([[ 3.0566308 , -0.8050177 ,  1.06781045],
       [ 6.33743502,  2.3009901 ,  1.30268101]])

In [61]:
np.random.randint(100, 50000)

41099

In [63]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [83]:
np.random.seed(5)
x1 = np.random.randint(20, size=6)
x1

array([ 3, 14, 15,  6, 16,  9])

In [85]:
np.array([[3,4,5,6,6],[9,4,5,2,4],[5,3,9,4,5]])

array([[3, 4, 5, 6, 6],
       [9, 4, 5, 2, 4],
       [5, 3, 9, 4, 5]])

In [89]:
import numpy as np
a = np.arange(49).reshape(7, 3)

ValueError: cannot reshape array of size 49 into shape (7,3)

In [97]:
import random

items = range(10)

results = []

while len(results) < 5:
    number = random.sample(items, 3)
    if number not in results:
        results.append(number)

print(results)

[[0, 4, 5], [6, 2, 7], [9, 7, 5], [7, 0, 4], [8, 5, 4]]


In [4]:
x5 = np.random.randint(10, size=(6,5))
x5

NameError: name 'np' is not defined