In [1]:
import numpy as np

In [4]:
# x5 = np.random.randint(10, size=(6,5))
# x5

array([[2, 9, 2, 2, 0],
       [8, 4, 0, 9, 4],
       [3, 7, 3, 2, 7],
       [0, 7, 7, 6, 0],
       [5, 2, 1, 3, 5],
       [4, 8, 3, 1, 7]])

In [5]:
# x2 = np.random.randint(10, size=(3,4))
# x2

array([[5, 1, 0, 7],
       [2, 2, 1, 6],
       [5, 0, 9, 7]])

In [12]:
x3 = np.random.randint(10, size=(4,4,5))
# print(x3[0])
# print(x3[0][2])
# x3[0][2][0]
# print(x3)
# x3[0,2,1]

x3.ndim

3

In [13]:
x3.size

80

In [18]:
x3.nbytes
x3.dtype
# print(type(x3))
# print(x3)

<class 'numpy.ndarray'>
[[[4 9 6 5 7]
  [6 0 5 9 7]
  [6 8 3 3 8]
  [6 6 6 3 6]]

 [[7 1 0 9 3]
  [7 6 1 3 7]
  [8 3 4 5 2]
  [1 2 4 9 6]]

 [[3 6 2 0 2]
  [0 6 5 2 5]
  [2 6 1 5 8]
  [6 5 0 7 3]]

 [[0 9 1 4 4]
  [5 7 7 7 9]
  [2 8 6 9 8]
  [4 6 1 5 2]]]


In [19]:
x3.itemsize

4

In [20]:
x3.size

80

In [22]:
x1 = ([8, 8, 6, 2, 8, 7])
x1[-2]

8

In [24]:
x1[4] = 2
x1

[8, 8, 6, 2, 2, 7]

In [25]:
x2.ndim

2

In [27]:
x3.ndim

3

In [56]:
x= np.arange(50).reshape(5, 10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [50]:
x.ndim

2

In [41]:
x[1::3]

array([1, 4, 7])

In [63]:
x = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
           [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
           [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
           [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
           [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
           [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
           [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
           [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
           [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]
        
            ([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
           [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
           [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
           [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])
             


SyntaxError: invalid syntax (1400540464.py, line 18)

In [ ]:
x = np.random.randint()